# Generated by Django 5.2 on 2025-05-03 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.year')),
            ],
        ),
    ]
