# Generated by Django 5.2 on 2025-05-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.account')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.section')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.section')),
            ],
        ),
    ]
