# Generated by Django 5.2 on 2025-05-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.activity')),
            ],
        ),
    ]
