# Generated by Django 6.0 on 2025-12-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0010_account_groups_account_is_active_account_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
